<?php
declare(strict_types=1);
function install_schema(PDO $pdo): array {
    $sql = [
        'cms_users' => 'CREATE TABLE IF NOT EXISTS cms_users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, display_name VARCHAR(160) NOT NULL, status ENUM("active","suspended") NOT NULL DEFAULT "active", is_primary TINYINT(1) NOT NULL DEFAULT 0, last_login DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_roles' => 'CREATE TABLE IF NOT EXISTS cms_roles (id INT AUTO_INCREMENT PRIMARY KEY, role_key VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, description VARCHAR(255) NOT NULL DEFAULT "", is_system TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_permissions' => 'CREATE TABLE IF NOT EXISTS cms_permissions (id INT AUTO_INCREMENT PRIMARY KEY, permission_key VARCHAR(140) NOT NULL UNIQUE, label VARCHAR(180) NOT NULL, module_key VARCHAR(80) NOT NULL, action VARCHAR(30) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_role_permissions' => 'CREATE TABLE IF NOT EXISTS cms_role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES cms_roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES cms_permissions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_user_roles' => 'CREATE TABLE IF NOT EXISTS cms_user_roles (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id,role_id), FOREIGN KEY(user_id) REFERENCES cms_users(id) ON DELETE CASCADE, FOREIGN KEY(role_id) REFERENCES cms_roles(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_modules' => 'CREATE TABLE IF NOT EXISTS cms_modules (module_key VARCHAR(80) PRIMARY KEY, is_enabled TINYINT(1) NOT NULL DEFAULT 1, menu_order INT NOT NULL DEFAULT 0, settings JSON NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_content' => 'CREATE TABLE IF NOT EXISTS cms_content (id BIGINT AUTO_INCREMENT PRIMARY KEY, module_key VARCHAR(80) NOT NULL, title VARCHAR(255) NOT NULL DEFAULT "", slug VARCHAR(255) NOT NULL DEFAULT "", status VARCHAR(40) NOT NULL DEFAULT "draft", data JSON NOT NULL, created_by INT NULL, updated_by INT NULL, published_at DATETIME NULL, deleted_at DATETIME NULL, deleted_by INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_module(module_key), KEY idx_status(status), KEY idx_content_trash(module_key,deleted_at), UNIQUE KEY uniq_module_slug(module_key,slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_media' => 'CREATE TABLE IF NOT EXISTS cms_media (id BIGINT AUTO_INCREMENT PRIMARY KEY, file_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL UNIQUE, mime_type VARCHAR(120) NOT NULL, file_size BIGINT NOT NULL, alt_text VARCHAR(255) NOT NULL DEFAULT "", caption TEXT NULL, uploaded_by INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_settings' => 'CREATE TABLE IF NOT EXISTS cms_settings (setting_key VARCHAR(150) PRIMARY KEY, setting_value LONGTEXT NULL, setting_type VARCHAR(30) NOT NULL DEFAULT "text", is_public TINYINT(1) NOT NULL DEFAULT 0, updated_by INT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_audit_logs' => 'CREATE TABLE IF NOT EXISTS cms_audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(150) NOT NULL, entity VARCHAR(100) NOT NULL DEFAULT "", entity_id BIGINT NULL, details JSON NULL, ip_address VARCHAR(45) NOT NULL DEFAULT "", created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_audit_created(created_at), KEY idx_audit_entity(entity,entity_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_mail_templates' => 'CREATE TABLE IF NOT EXISTS cms_mail_templates (id INT AUTO_INCREMENT PRIMARY KEY, template_key VARCHAR(100) NOT NULL UNIQUE, subject VARCHAR(255) NOT NULL, body LONGTEXT NOT NULL, status ENUM("active","disabled") NOT NULL DEFAULT "active", updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_sent_mail' => 'CREATE TABLE IF NOT EXISTS cms_sent_mail (id BIGINT AUTO_INCREMENT PRIMARY KEY, to_email VARCHAR(190) NOT NULL, to_name VARCHAR(190) NOT NULL DEFAULT "", cc TEXT NULL, bcc TEXT NULL, subject VARCHAR(255) NOT NULL, body LONGTEXT NOT NULL, in_reply_to BIGINT NULL, status ENUM("sent","failed") NOT NULL, error_message VARCHAR(1000) NULL, sent_by INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_sent_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'cms_categories' => 'CREATE TABLE IF NOT EXISTS cms_categories (id INT AUTO_INCREMENT PRIMARY KEY, module_key VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM("active","disabled") NOT NULL DEFAULT "active", created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uniq_module_category(module_key,slug), KEY idx_category_module(module_key,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
    ];
    foreach ($sql as $table=>$statement) $pdo->exec($statement);
    foreach (cfg('modules',[]) as $key=>$def) $pdo->prepare('INSERT IGNORE INTO cms_modules(module_key,is_enabled,menu_order) VALUES(?,?,?)')->execute([$key,1,0]);
    $actions=['read','create','update','delete'];
    foreach (cfg('modules',[]) as $module=>$def) foreach($actions as $action) $pdo->prepare('INSERT IGNORE INTO cms_permissions(permission_key,label,module_key,action) VALUES(?,?,?,?)')->execute(["$module.$action",ucfirst($action).' '.$def['label'],$module,$action]);
    $pdo->prepare('INSERT IGNORE INTO cms_roles(role_key,name,description,is_system) VALUES("super_admin","Super Administrator","Full access except protection rules are enforced for the primary administrator.",1),("administrator","Administrator","Configurable access to selected modules.",0),("editor","Editor","Content editing access.",0),("author","Author","Create and update assigned content.",0)')->execute();
    $roleId=(int)$pdo->query('SELECT id FROM cms_roles WHERE role_key="super_admin"')->fetchColumn();
    $pdo->exec("INSERT IGNORE INTO cms_role_permissions(role_id,permission_id) SELECT $roleId,id FROM cms_permissions");
    $securityModules=['users','roles','audit','settings','backups'];
    $securityPlaceholders=implode(',',array_fill(0,count($securityModules),'?'));
    $administratorId=(int)$pdo->query('SELECT id FROM cms_roles WHERE role_key="administrator"')->fetchColumn();
    $administratorStatement=$pdo->prepare("INSERT IGNORE INTO cms_role_permissions(role_id,permission_id) SELECT ?,id FROM cms_permissions WHERE module_key NOT IN ($securityPlaceholders)");
    $administratorStatement->execute(array_merge([$administratorId],$securityModules));
    $contentOnlyModules=array_keys(array_filter(cfg('modules',[]),static fn(array $def): bool => !($def['system']??false)));
    $contentPlaceholders=implode(',',array_fill(0,count($contentOnlyModules),'?'));
    foreach(['editor','author'] as $roleKey){
        $roleForContent=(int)$pdo->query("SELECT id FROM cms_roles WHERE role_key=\"$roleKey\"")->fetchColumn();
        $statement=$pdo->prepare("INSERT IGNORE INTO cms_role_permissions(role_id,permission_id) SELECT ?,id FROM cms_permissions WHERE action IN ('read','create','update') AND module_key IN ($contentPlaceholders)");
        $statement->execute(array_merge([$roleForContent],$contentOnlyModules));
    }
    return array_keys($sql);
}
